schema_version: 1

context:
  name: pydoclint
  version: "0.8.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydoclint-${{ version }}.tar.gz
  sha256: e453a6ea4e8f1fc30e9901564c65961bc3435df9810d64237d18ed7ea0bd5902

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pydoclint = pydoclint.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - click >=8.1.0
    - docstring_parser_fork >=0.0.12
    - tomli >=2.0.1

tests:
  - python:
      imports:
        - pydoclint
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pydoclint --help

about:
  homepage: https://github.com/jsh9/pydoclint
  summary: A Python docstring linter that checks arguments, returns, yields, and raises sections
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
